INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Acre',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'AC', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Alagoas',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'AL', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Amapá',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'AP', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Amazonas',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'AM', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Bahia',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'BA', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Ceará',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'CE', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Distrito Federal',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'DF', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Espírito Santo',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'ES', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Goiás',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'GO', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Maranhão',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'MA', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Mato Grosso',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'MT', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Mato Grosso do Sul',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'MS', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Minas Gerais',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'MG', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Pará',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'PA', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Paraíba',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'PB', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Paraná',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'PR', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Pernambuco',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'PE', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Piauí',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'PI', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Rio de Janeiro',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'RJ', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Rio Grande do Norte',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'RN', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Rio Grande do Sul',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'RS', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Rondônia',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'RO', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Roraima',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'RR', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Santa Catarina',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'SC', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('São Paulo',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'SP', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Sergipe',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'SE', 'victor');
INSERT INTO su_estados (nome_estado, id_pais, sigla_estado, usuario) VALUES ('Tocantins',(SELECT id_chave_pais from su_paises WHERE nome_pais like 'Brasil') ,'TO', 'victor');
